package io.HappySwimwear.Controlador;

import io.HappySwimwear.Modelo.AuthenticationRequest;
import io.HappySwimwear.Modelo.AuthenticationResponse;
import io.HappySwimwear.Modelo.User;
import io.HappySwimwear.Repositorio.UserRepository;
import io.HappySwimwear.Servicio.MyUserDetailsService;
import io.HappySwimwear.Util.JwtUtil;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@CrossOrigin("*")
@Controller // This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    private MyUserDetailsService miUserDetailsService;

    @Autowired
    private JwtUtil jwtTokenUtil;

    //API servicios , endpoints disponibles
    //primero se debe verificar/autentificar, sacando una jwt en
    //el endpoint /verificacion con metodo POST y en el body → {"username":"correo de algun usuario en la database", "password":"el contraseña de ese usuario"
    //usar el jwt en el header = key Authorization  value "Bearer Aqui el jwt que se genero"

    //POST  http://localhost:8080/verificacion
    @PostMapping(path = "/verificacion")
    //GENERAR TOKEN JWT solo a usuarios registrados
    public ResponseEntity<?> generarTokenVerificacion(@RequestBody AuthenticationRequest solicitudVerificacion) throws Exception {
        try {
            authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(solicitudVerificacion.getUsername(), solicitudVerificacion.getPassword())
            );
        } catch (BadCredentialsException e) {
            throw new Exception("No se encontro ningun usuario con el correo: " + solicitudVerificacion.getUsername(), e);
        }


        final UserDetails miUsuarioDetalles = miUserDetailsService
                .loadUserByUsername(solicitudVerificacion.getUsername());//get correo, verifica correo no nombre

        final String jwt = jwtTokenUtil.generateToken(miUsuarioDetalles);

        return ResponseEntity.ok(new AuthenticationResponse(jwt));
    }

    //GET  http://localhost:8080/todos
    @GetMapping(path = "/todos") //MUESTRA TODOS LOS USUARIOS  http://localhost:8080/all
    public @ResponseBody
    ResponseEntity<Iterable<User>> getAllUsers() {
        // This returns a JSON or XML with the users
        return new ResponseEntity<>(userRepository.findAll(), HttpStatus.OK);
    }

    //GET  http://localhost:8080/usuario/2
    @GetMapping(path = "/usuario/{id}") //MUESTRA SOLO UN USUARIO
    public ResponseEntity<Object> getUser(@PathVariable int id) {
        if (userRepository.existsById(id)) {
            return new ResponseEntity<>(userRepository.findById(id), HttpStatus.OK);
        } else {
            return new ResponseEntity<>("El usuario con el id: " + id + " NO existe", HttpStatus.NOT_FOUND);
        }
    }

    //POST  http://localhost:8080/agregar
    @PostMapping(path = "/agregar") // Map ONLY POST Requests
    public ResponseEntity<Object> addNewUser(@RequestBody User user) {
        userRepository.save(user);
        return new ResponseEntity<>("El usuario:\n" + user.getId_usuario() + " " + user.getNombre() + "  " + user.getCorreo() + "\nSe ha registrado con etxsito", HttpStatus.CREATED);
    }

    //PUT  http://localhost:8080/modificar/1  el numero id del que queremos modificar
    @PutMapping(path = "/modificar/{id}") //Actualizar registro
    public ResponseEntity<Object> updateUser(@PathVariable int id, @RequestBody User user) {
        User nuevo = new User();
        nuevo = userRepository.findById(id);
        nuevo.setId_usuario(user.getId_usuario());
        nuevo.setNombre(user.getNombre());
        nuevo.setCorreo(user.getCorreo());
        nuevo.setDireccion(user.getDireccion());
        nuevo.setTelefono(user.getTelefono());
        nuevo.setCompras(user.getCompras());
        nuevo.setContrasena(user.getContrasena());
        userRepository.save(nuevo);
        return new ResponseEntity<>("Usuario: " + id + "\n fue actualizado etsitozamente", HttpStatus.ACCEPTED);
    }

    //DELETE  http://localhost:8080/usuario/1
    @DeleteMapping(path = "/usuario/{id}") //ELIMINA UN USUARIO
    public @ResponseBody
    String deleteUser(@PathVariable Integer id) {
        userRepository.deleteById(id);
        return "usuario con id: " + id + " Se ha borrado de la databeis pá siempre";//no va a encontrar a nadie porque ya esta borrado
    }
}


